#pragma once

#define PS2_REG_DATA 0x60
#define PS2_REG_COMMAND 0x64
#define PS2_REG_STATUS 0x64

#define PS2_CMD_READ_CONFIG_BYTE 0x20
#define PS2_CMD_WRITE_CONFIG_BYTE 0x60
#define PS2_CMD_DISABLE_SECOND_PORT 0xA7
#define PS2_CMD_ENABLE_SECOND_PORT 0xA8
#define PS2_CMD_TEST_SECOND_PORT 0xA9
#define PS2_CMD_TEST 0xAA
#define PS2_CMD_TEST_FIRST_PORT 0xAB
#define PS2_CMD_DISABLE_FIRST_PORT 0xAD
#define PS2_CMD_ENABLE_FIRST_PORT 0xAE
#define PS2_CMD_SELECT_SECOND_INPUT 0xD4

#define PS2_DEV_CMD_IDENTIFY 0xF2
#define PS2_DEV_CMD_ENABLE_SCAN 0xF4
#define PS2_DEV_CMD_DISABLE_SCAN 0xF5
#define PS2_DEV_CMD_RESET 0xFF

#define PS2_DEV_ACK 0xFA

#define PS2_TIMEOUT 10

#define WriteCommand(command)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    while (inb(PS2_REG_STATUS) & 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \
        ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
    outb(PS2_REG_COMMAND, command)

#define ReadData(value)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
    while (!(inb(PS2_REG_STATUS) & 1))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
        ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
    value = inb(PS2_REG_DATA)

#define WriteData(value)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    while (inb(PS2_REG_STATUS) & 2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \
        ;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
    outb(PS2_REG_DATA, value)

char scancodeToChar[] = {'\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '`', '\0', '\0', '\0', '\0', '\0', '\0', 'Q', '1', '\0', '\0', '\0', 'Z', 'S', 'A', 'W', '2', '\0', '\0', 'C', 'X', 'D', 'E', '4', '3', '\0', '\0', ' ', 'V', 'F', 'T', 'R', '5', '\0', '\0', 'N', 'B', 'H', 'G', 'Y', '6', '\0', '\0', '\0', 'M', 'J', 'U', '7', '8', '\0', '\0', ',', 'K', 'I', 'O', '0', '9', '\0', '\0', '.', '/', 'L', ';', 'P', '-', '\0', '\0', '\0', '\'', '\0', '[', '='};
